### ISSUE TITLE
Venn() does not generate image

### ISSUE THREAD

**Issue by RomanticStrings** [LankyCyril/pyvenn#10]
I follow the minimal example in the description page, but when I run the module (IDLE), though it throws no error, it does not generate any image.

**Comment by LankyCyril** [comment]
The minimal example was written to work in Jupyter notebooks, so the figures appear automagically because of `%matplotlib inline`.

Because it's not a Jupyter notebook in your case, the automatic displaying of figures is not enabled. To see your figure, you should do something like this:

```
>>> from matplotlib import pyplot as plt
>>> # do your venn stuff here
>>> plt.show()
```

**Comment by RomanticStrings** [comment]
Thank you, LankyCyril. I knew there was something about interactive, but I'm in just a little over my head here!
