### ISSUE TITLE
sizing

### ISSUE THREAD

**Issue by iamjli** [LankyCyril/pyvenn#4]
Loving how much more user friendly your package is over the alternatives!

Is there a way to make the size of the circles (at least for 2 and 3 comparisons) based on the size of the sets?

**Comment by LankyCyril** [comment]
Not yet... It's in the roadmap, though.
Sizing for 2 and 3 sets is implemented in `matplotlib-venn` and for now that's the one I'm using myself when I need proportional circles :D
