### ISSUE TITLE
non-interactive/batch example to image file?

### ISSUE THREAD

**Issue by chickenandpork** [LankyCyril/pyvenn#5]
Can you create or describe an example that produces an image file?  I'd like to leverage your work to quickly produce diagrams, but I'm not a matplot user, and I don't see where any file is written out.

For context, I tried:
```
pip3 install --user venn 
grep -v '^%' your-minimal-musician-example | tee musician.py
  from venn import venn

 musicians = {
     "Members of The Beatles": {"Paul McCartney", "John Lennon", "George Harrison", "Ringo Starr"},
     "Guitarists": {"John Lennon", "George Harrison", "Jimi Hendrix", "Eric Clapton", "Carlos Santana"},
     "Played at Woodstock": {"Jimi Hendrix", "Carlos Santana", "Keith Moon"}
  }
  venn(musicians)

python3 musician.py
```

The file runs once the `%matplotlib inline` is removed, but the result doesn't export the generated object as an image.  Perhaps it's trying to manipulate a running matplot process?

**Comment by LankyCyril** [comment]
Hi! In a non-interactive environment you can use the `Axes` object returned by the `venn()` function:
```{python}
ax = venn(musicians)
ax.figure.savefig("musicians.png", bbox_inches="tight")
```
When run inside the notebook, jupyter just recognizes that an Axes object has been returned and displays it.
