### ISSUE TITLE
I try to import venn but it doesn't work

### ISSUE THREAD

**Issue by JohanDelValleV** [LankyCyril/pyvenn#6]
When I try to import venn:
   `from venn import venn`
I have the next error:
> import venn
> ModuleNotFoundError: No module named 'venn'

**Comment by JohanDelValleV** [comment]
> When I try to import venn:
> `from venn import venn`
> I have the next error:
> 
> > import venn
> > ModuleNotFoundError: No module named 'venn'

BTW i have installed venn with:
`pip install venn`

**Comment by LankyCyril** [comment]
Are you running it as a script or from an interactive session (like Jupyter, ipython, ptpython etc)?

**Comment by JohanDelValleV** [comment]
No, im not using an interactive session

**Comment by LankyCyril** [comment]
It could be that the python version that you're running your script with is different from the pip version you installed venn with (like 2.7 vs 3), or you're using pip and python from different environments.

What do these commands output? `pip --version`, `which pip`, `python --version`, and `which python`

Also, please add this at the top of your python script (*before* you import venn): `import sys; print(sys.executable, sys.version)` and let me know what it outputs.

**Comment by LankyCyril** [comment]
The issue has been inactive for 6 months – closing it now. Feel free to open a new one if the question remains.
