### ISSUE TITLE
pyvenn with matplolib subplots

### ISSUE THREAD

**Issue by tiagocabralborelli** [LankyCyril/pyvenn#9]
Hello.
Recently I was trying to plot a Venn diagram in a matplotlib subplot but it always goes out of the plot. Is there a way to insert it back?

**Comment by LankyCyril** [comment]
Hi! Can you provide a minimal example where this happens?

**Comment by tuhinsharma121** [comment]
@tiagocabralborelli you may check the example - https://github.com/LankyCyril/pyvenn/blob/master/pyvenn-demo.ipynb this might help you.
